#!/usr/bin/bash
# waybar -c $HOME/.config/hypr/component/waybar/config -s $HOME/.config/hypr/component/waybar/style.css &
# waybar -c $HOME/.config/waybar/config.jsonc -s $HOME/.config/waybar/style.hcss & disown
waybar &
