#!/bin/bash

HYPR_SCRPTS=$HOME/.config/hypr/scripts
AC_STATUS=$(cat /sys/class/power_supply/AC/online)  # 1 means AC power is connected, otherwise 0
MONITOR_STATUS=$(hyprctl monitors | grep '(ID 1)') # Replace HDMI-1 with your external monitor's id

if [[ "$AC_STATUS" -eq 1 && -n "$MONITOR_STATUS" ]]; then
    hyprctl keyword monitor eDP-1,disable
    $HYPR_SCRPTS/reset_waybar
    notify-send "it worked"
else
    notify-send "sadd face"
fi

