#!/usr/bin/bash
FILE=$(xdg-user-dir PICTURES)/screenshots/$(date +'%Y%m%d_%H%M%S.png')

grim -g "$(slurp)" $FILE | wl-copy
wl-copy <$FILE

notify-send --icon ~/.config/hypr/assets/square.png 'Screenshot Saved'
# viewnior $FILE
