#!/bin/bash

HYPR_SCRPTS=$HOME/.config/hypr/scripts

swayidle \
    timeout 300 $HYPR_SCRPTS/lock \
    timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
    timeout 3600 'systemctl suspend' \
    before-sleep $HYPR_SCRPTS/lock & 

