#!/bin/bash

HYPR_SCRPTS=$HOME/.config/hypr/scripts

swayidle \
	timeout 900 $HYPR_SCRPTS/lock \
	timeout 1800 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
	before-sleep $HYPR_SCRPTS/lock &
# timeout 3601 'systemctl suspend' \
