#!/usr/bin/bash
source $HOME/.profile

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &
thunderbird &
config-init.sh &
$scripts/tmux_init.sh &

# $scripts/swidle &

# wallpaper
# $scripts/wall $config/wallpapers/4.jpg &

# effects
# $scripts/rgb &

# other
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
server_linux_debug >>~/.var/log/disc-rpc-ext.txt
