#!/usr/bin/bash
source $HOME/.profile

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/tmux_init.sh &
$scripts/launch_waybar &
$scripts/tools/dynamic &

$scripts/swidle &

# wallpaper
# $scripts/wall $config/wallpapers/4.jpg &

swaybg -m fill -i $config/wallpapers/1.jpg
thunderbird &
discord &
signal-desktop &
config-init.sh &
# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a aurora "hello $(whoami)" &
